In [4]:
import pandas as pd
import numpy as np
import matplotlib
import os

In [5]:
if not os.path.isfile('data.csv'):
    data = open('data.csv', mode='w')
    
    row = list()
    files=['/Users/sarahhan/data_folder/combined_data_1.txt','/Users/sarahhan/data_folder/combined_data_2.txt', 
           '/Users/sarahhan/data_folder/combined_data_3.txt', '/Users/sarahhan/data_folder/combined_data_4.txt']
    for file in files:
        print("Reading ratings from {}...".format(file))
        with open(file) as f:
            for line in f: 
                del row[:]
                line = line.strip()
                if line.endswith(':'):
                    movie_id = line.replace(':', '')
                else:
                    row = [x for x in line.split(',')]
                    row.insert(0, movie_id)
                    data.write(','.join(row))
                    data.write('\n')
    data.close()

In [6]:
df = pd.read_csv('data.csv', sep=',', 
                       names=['movie', 'user','rating','date'])
df.date = pd.to_datetime(df.date)
df.sort_values(by='date', inplace=True)
print("Starting...")
df['year'] = pd.to_datetime(df['date']).dt.year
print("Finishing Year...")
df['month'] = pd.to_datetime(df['date']).dt.month
print("Finishing Month...")
df['day'] = pd.to_datetime(df['date']).dt.month
print("Done")

Starting...
Finishing Year...
Finishing Month...
Done


In [7]:
df = df.drop(columns=["date"])
df

movie     user  rating  year  month  day
56431994  10341   510180       4  1999     11   11
9056171    1798   510180       5  1999     11   11
58698779  10774   510180       3  1999     11   11
48101611   8651   510180       2  1999     11   11
81893208  14660   510180       2  1999     11   11
...         ...      ...     ...   ...    ...  ...
49939086   8993  2183787       4  2005     12   12
42072268   7430   258170       4  2005     12   12
47098649   8467  1534359       5  2005     12   12
55621336  10168  2543295       2  2005     12   12
25464092   4736  1346243       5  2005     12   12

[100480507 rows x 6 columns]

In [8]:
df_small = df.sample(1000)
y = df_small['rating']
X = df_small.drop(columns=['rating'])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
print("fitting model...")
svclassifier.fit(X_train, y_train)

fitting model...


SVC(kernel='linear')

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 0  0  3  9  0]
 [ 0  0  2 16  0]
 [ 0  1 11 41  0]
 [ 0  3  6 63  0]
 [ 0  1  8 34  2]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        12
           2       0.00      0.00      0.00        18
           3       0.37      0.21      0.27        53
           4       0.39      0.88      0.54        72
           5       1.00      0.04      0.09        45

    accuracy                           0.38       200
   macro avg       0.35      0.23      0.18       200
weighted avg       0.46      0.38      0.28       200



/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _wa